version: '3.7'

services:
  interface:
    build: 
      context: ./view
    networks:
      - pbl-network
    ports:
      - "3000:3000"
  broker:
    build:
      context: ./broker
    stdin_open: true
    tty: true
    hostname: broker
    networks:
      - pbl-network
    ports:
      - "8888:8888"
      - "8889:8889/udp"
      - "8082:8082"
  device:
    build:
      context: ./device
    stdin_open: true
    tty: true
    networks:
      - pbl-network

networks:
  pbl-network:
    driver: bridge